stylesheets:
  - style.css

default_page: windows

window:
  height: 500
  width: 1000

image:
  resize_size: 200
  widget_size: 150

classes:
  window: window
  image_card: card
  image_card_loading: card-loading
  image: image
  image_label: image-label
  notebook: notebook
  tab_label: tab-label
  notebook_page: page
  region_button: region-button
  restore_button: restore-button

windows:
  min_per_row: 3
  max_per_row: 999
  clicks: 2
  spacing: 12

outputs:
  clicks: 2
  spacing: 6
  show_label: false
  respect_output_scaling: true

region:
  command: slurp -f '%o@%x,%y,%w,%h'

hide_token_restore: false
debug: false